DEFAULT_PAD_TOKEN = "[PAD]"
DEFAULT_EOS_TOKEN = "</s>"
DEFAULT_BOS_TOKEN = "</s>"
DEFAULT_UNK_TOKEN = "</s>"

KEY_START_TOKEN = "<KEY_START>"
KEY_END_TOKEN = "<KEY_END>"

VALUE_START_TOKEN = "<VALUE_START>"
VALUE_END_TOKEN = "<VALUE_END>"

TRAIN_EXAMPLE_START_TOKEN = "<EXAMPLE_START>"
TRAIN_EXAMPLE_END_TOKEN = "<EXAMPLE_END>"

CONTEXT_START_TOKEN = "<CONTEXT_START>"
CONTEXT_END_TOKEN = "<CONTEXT_END>"

META_START_TOKEN = "<META_START>"
META_END_TOKEN = "<META_END>"

PREFIX_START_TOKEN = "<PREFIX_START>"
PREFIX_END_TOKEN = "<PREFIX_END>"

QUANTILE_START_TOKEN = "<QUANTILE_START>"
QUANTILE_END_TOKEN = "<QUANTILE_END>"

SCALE_START_TOKEN = "<SCALE_START>"
SCALE_END_TOKEN = "<SCALE_END>"

SUFFIX_START_TOKEN = "<SUFFIX_START>"
SUFFIX_END_TOKEN = "<SUFFIX_END>"

CHOICES_START_TOKEN = "<CHOICES_START>"
CHOICES_END_TOKEN = "<CHOICES_END>"
IGNORE_INDEX = -100

# Follow the OpenAI fine-tuning guide (and also LiFT)
# https://platform.openai.com/docs/guides/fine-tuning/preparing-your-dataset
QA_SEP_TOKEN = "<|endinput|>"  # Separates the question (inputs) from answer (labels).
EOC_TOKEN = "<|endcompletion|>"  # Indicates end of completion.
ANS_CHOICES_SEP_TOKEN = "||"
